customer.params.x=44
customer.params.y=11
spring.datasource.url=jdbc:h2:mem:customers
#when config repo was modified (commit code && call the following api
#POST http://localhost:8888/CUSTOMER-SERVICE/actuator/refresh
#Accept: application/json